name: 'Feature Request'
description: Suggest a feature for MonsterJS Framework

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which @monster-js/* package(s) are relevant/related to the feature request?
      options:
        - cli
        - core
        - docs
        - router
        - store
        - tester
        - transformer
      multiple: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
