name: NPM Publish

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: Publish NPM packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Publish packages
        run: npm install && npm run lint && npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}